### ISSUE TITLE
copyright violation

### ISSUE THREAD

**Issue by penn5** [mashed-potatoes/PotatoNV-crossplatform#1]
I am happy to license this code under agpl3. It is now legal as long as you put a valid copyright notice stating the original author

**Comment by R0rt1z2** [comment]
pfffft

**Comment by mashed-potatoes** [comment]
> pfffft

what? 😄

**Comment by R0rt1z2** [comment]
> > pfffft
> 
> what? 😄

Nothing, I was just browsing your repos until I came across this "copyright violation", which is funny because he (the so called original author) just kanged the original hikey tool and added a bunch of stuff. 

Anyway, I'm really glad to see you're still around. Hope you and your family are doing okay, it would be cool to see you around Telegram again.

**Comment by penn5** [comment]
Hello. My code was written by me, using the protocol that was reverse engineered from the 96boards tool.

**Comment by AntiEngineer** [comment]
> Hello. My code was written by me, using the protocol that was reverse engineered from the 96boards tool.

100% real no fake. totally legitimate.

**Comment by halal-beef** [comment]
> > Hello. My code was written by me, using the protocol that was reverse engineered from the 96boards tool.
> 
> 100% real no fake. totally legitimate.

(Working 2024/2029)

**Comment by ItsVixano** [comment]
> > > Hello. My code was written by me, using the protocol that was reverse engineered from the 96boards tool.
> > 
> > 
> > 100% real no fake. totally legitimate.
> 
> (Working 2024/2029)

Descarga Mediafire link

**Comment by AntiEngineer** [comment]
> > Hello. My code was written by me, using the protocol that was reverse engineered from the 96boards tool.
> 
> 100% real no fake. totally legitimate.

I seriously can't believe where the stupidity of people can go. 
I thought the little guy had changed by now but he's still the same. 

Reverse engineered from the 96boards tool? what the hell you mean.

**Comment by halal-beef** [comment]
96Boards :trollface: tool

**Comment by ItsVixano** [comment]
96board bye bye tool

go @ Roger

**Comment by plarfman** [comment]
> Hello. My code was written by me, using the protocol that was reverse engineered from the 96boards tool.

96boards OSS RE tool go @ app translation5
